### PR TITLE
Cuteness

### PR DESCRIPTION
**Pull request by vbatts**
closes: #37

### CODE REVIEW

**Comment by vbatts** [comment]
cc @maraino

**Comment by maraino** [comment]
Hi @vbatts, I think there were more emojis that were not right, you should compare them with my gist, for example, I remember that ®️ wasn't right too, and I think there are others.
https://gist.github.com/maraino/5a15ced81d5467cd408ee07adbe88eb4

**Comment by vbatts** [comment]
On 23/11/21 10:45 -0800, Mariano Cano wrote:
>Hi @vbatts, I think there were more emojis that were not right, you should compare them with my gist, for example, I remember that ®️ wasn't right too, and I think there are others.
>https://gist.github.com/maraino/5a15ced81d5467cd408ee07adbe88eb4

I ran that code, but didn't immediately see the comparison of cute
emojis.

**Comment by vbatts** [comment]
@maraino what terminal and environment are you using?

From your gist, a number of them are maybe too fancy for some terminals.
image

Finding the lowest-common-denominator was part of this effort.

**Comment by maraino** [comment]
I use iTerm2 (macOS), but you should not care about those emojis, just to the codes below that I got from https://github.com/kyokomi/emoji/blob/master/emoji_codemap.go, the library used in main.go

**Comment by maraino** [comment]
image

**Comment by maraino** [comment]
image

**Comment by vbatts** [comment]
@maraino so what are the specific things to address here?

**Pull request merged**
